### ISSUE TITLE
Incorrect content wrapping with read-only fields

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#1469]
In some circumstances we have seen read-only content of Input components wrap in unexpected places. This is due to using the following CSS:

``` css
.wc-ro-input {
  word-break: break-all;
}
```

This CSS was applied to overcome a specific issue in a down-stream consumer so was not appropriate for a framework.
